language: python

cache: pip

python:
    - "3.6"
    - "3.6-dev"
    - "3.7"
    - "3.7-dev"
    - "3.8"
    - "3.8-dev"

install:
    - pip install poetry
    # Blocker: https://github.com/python-poetry/poetry/issues/1009
    - pip install mypy
    - poetry build
    - pip install dist/*.whl

script:
    - poetry run nosetests-3.4 --with-coverage --cover-package=pymispgalaxies -d
    - poetry run mypy .

after_success:
    - poetry run codecov
    - poetry run coveralls
